### ISSUE TITLE
Error: Can't use CovarExtract()

### ISSUE THREAD

**Issue by lixiaoxiong** [statnmap/SDMSelect#1]
I use my own environment grid, but I cannot use CovarExtract (), suggesting Error in rgdal :: showEPSG (x): Can't parse PROJ.4-style parameter string

**Comment by statnmap** [comment]
I would need a reproducible example to try to find why you have a problem.
Could you provide a subset of your dataset that reproduces the problem ?

**Comment by statnmap** [comment]
Without news on this error, I decide to close it.  
Feel free to re-open if you have a reproducible example that leads to this error.  
Thank you.
