### ISSUE TITLE
SDMSelect installation issue in RStudio on Windows 10

### ISSUE THREAD

**Issue by Saadi4469** [statnmap/SDMSelect#3]
Hello,

When I try installing SDMSelect using:
`
remotes::install_github("statnmap/SDMSelect")`

It gives me a list of packages to update, so I enter 3 and skip updating. But then I get this error:

```
Error: Failed to install 'SDMSelect' from GitHub:
  (converted from warning) installation of package ‘C:/Users/saadb/AppData/Local/Temp/RtmpGMW07o/file41e45f1347e9/SDMSelect_0.1.6.tar.gz’ had non-zero exit status
```

How can I fix this issue?

**Comment by Saadi4469** [comment]
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE) fixes the issue.

**Comment by statnmap** [comment]
I think you did not really installed {SDMSelect}. You will need find in the log which package failed to install.  
Could you share the complete log from `remotes::install_github("statnmap/SDMSelect")` ?

**Comment by Saadi4469** [comment]
Sure, this is what I get upon running the above line:
```
Skipping install of 'SDMSelect' from a github remote, the SHA1 (8f0e3c3d) has not changed since last install.
  Use `force = TRUE` to force installation
```

**Comment by statnmap** [comment]
Ok, so you successfully installed {SDMSelect}. There is no more errors apparently.
